### ISSUE TITLE
Maintaining live chart data

### ISSUE THREAD

**Issue by DavHanna** [Bittrex/beta#9]
My goal is to maintain a live updated copy of the price charts with the volumes for all pairs and for several intervals.
I'm trying to achieve this by:
1- Subscribing to exchange deltas for all pairs, and calculating all the candles with every new trade.
2- Synchronizing the old candles data using the GetTicks endpoint of the REST API.

The first step is okay, the second step has 2 problems:
1- The ticks returned by the API for smaller time intervals (oneMin, fiveMin) do not include the latest candles. Usually the oneMin response excludes the latest 3-4 candles, and the fiveMin response excludes the latest candle.
2- The ticks returned for larger time intervals, supposing that they really are updated to the latest second, are not guaranteed to sync well with the live trade data I'm getting.
A simple error scenario would be a trade that happened at the time of syncing, the trade will (presumabely) be included in the latest candle of the REST API response, but will be calculated again by my application, which will lead to adding the trade volume twice, and possibly having a misleading close price for the current candle, or a misleading open price for the next candle.

Am I even doing this right, or is there a better way to achieve the goal?
If this is the only way, how can I implement it correctly and reliably?

Note: I'm aware of QueryExchangeState, which returns the fills for the last 20-25 minutes.
This will solve the problem for smaller time intervals because each fill has an ID and a timestamp, so I can easily discard the duplicates. But Problem 2 remains for larger time intervals (1 hour, 4 hours, 1 day...).

**Comment by pwnzya** [comment]
Hello.

I'm also tackling the same issue.

As you all know, the commands GetTicks and GetLatestTick are part of undocumented version 2.0 of Bittrex REST API.  (Unofficially they are documented [here](https://github.com/thebotguys/golang-bittrex-api/wiki/Bittrex-API-Reference-(Unofficial)).)

The issue is that GetTicks' returned data doesn't include the latest tick, nor does GetLatestTick's returned data, at the time of tick or soon after. (There is a delay of aprox. 3 to 6 min.)
For example, if I call GetTicks for a market for fiveMin interval at time 17:01, then the data returned by GetTicks should include the tick data for time 17:00, but it doesn't.  It's aprox. 3 to 6 min after 17:00 that the returned data are updated to include the tick for time 17:00.
If I remember correctly from my tests, the delay is there for all intervals.  My apology if it's not exactly I described here.

It would be nice if there were websocket endpoints for monitoring latest ticks for all markets for all intervals, and GetTicks didn't have the delay.

Thanks.

**Comment by pdotmidge** [comment]
We're definitely considering websocket-based tick streams that will help you do a better job of what you want to do, but the existing API will not get you all the way there.

- Currently-provided tick data are not real-time.
- On an individual market basis (e.g. `SubscribeToExchangeDeltas`) we update roughly every 1000ms.
- On an exchange-wide basis (e.g. `SubscribeToSummary[Lite]Deltas`) we update roughly every 5000ms.

As you've stated, the 2.0 API is unsupported and undocumented and could evaporate at any time, beware taking a dependency on it.

**Comment by laserlance** [comment]
@DavHanna To calculate candles correctly you need to ensure that you're timestamps are synchronized. From your statement that you calculate candles as they arrive, I gather that you're not synchronizing. You cannot calculate candles for the current minute until that minute has closed--for 1-minute periods. 
To fill the time gap that presently exists for Bittrex candles you can use a third-party service like [Cluedex.com](https://www.cluedex.com/api) which calculates the candles for you.

**Comment by slidenerd** [comment]
- @pdotmidge Is the 3.0 API having anything to do live candles, 
- have you guys taken a look at other Exchange APIs where kline streams are being offered? 
- I cannot find kline streams on your 3.0 docs anywhere. 
- Could you add an example of building live candles from trades or something because we want to know what process you are considering, some exchanges take the average of bid and ask, some consider the ask price, some consider the bid price, some exchanges build candles from tickers, which method does Bittrex follow
